/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RMIClient;

import Controllers.CreateAccountController;
import Controllers.DeleteAccountController;
import Controllers.LoginController;
import Controllers.NotifyAllController;
import Controllers.UpdateAccountController;
import java.rmi.RemoteException;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Toumie
 */
public class AdminFunc extends javax.swing.JFrame {

    /**
     * Creates new form AdminFunc
     */
    Registry r;
    CreateAccount ac;
    public AdminFunc() {
        initComponents();
    }

        public JButton getCreateAccountButton() {
        return CreateAccountButton;
    }

    public JButton getUpdateAccountButton() {
        return UpdateAccountButton;
    }
    
    public JButton getDeleteAccountButton() {
        return DeleteAccountButton;
    }
    
     public JButton getNotifyAllButton() {
        return NotifyAllButton;
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        CreateAccountButton = new javax.swing.JButton();
        UpdateAccountButton = new javax.swing.JButton();
        DeleteAccountButton = new javax.swing.JButton();
        NotifyAllButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 206, 108));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Admin Functionalities");

        CreateAccountButton.setBackground(new java.awt.Color(255, 255, 153));
        CreateAccountButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CreateAccountButton.setText("Create Account");
        CreateAccountButton.setAutoscrolls(true);
        CreateAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountButtonActionPerformed(evt);
            }
        });

        UpdateAccountButton.setBackground(new java.awt.Color(153, 255, 153));
        UpdateAccountButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UpdateAccountButton.setText("Update Account");
        UpdateAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateAccountButtonActionPerformed(evt);
            }
        });

        DeleteAccountButton.setBackground(new java.awt.Color(255, 102, 255));
        DeleteAccountButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DeleteAccountButton.setText("Delete Account");
        DeleteAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAccountButtonActionPerformed(evt);
            }
        });

        NotifyAllButton.setBackground(new java.awt.Color(153, 153, 255));
        NotifyAllButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NotifyAllButton.setText("Notify All");
        NotifyAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotifyAllButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CreateAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(UpdateAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                    .addComponent(DeleteAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NotifyAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 101, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addComponent(CreateAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(UpdateAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(DeleteAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(NotifyAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void NotifyAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotifyAllButtonActionPerformed
        try {
            // TODO add your handling code here:
            NotifyAllController mm = new NotifyAllController();
            
        } catch (RemoteException ex) {
            Logger.getLogger(AdminFunc.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_NotifyAllButtonActionPerformed

    private void DeleteAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAccountButtonActionPerformed
        try {
            // TODO add your handling code here:
            DeleteAccountController cc = new DeleteAccountController();
            
        } catch (RemoteException ex) {
            Logger.getLogger(AdminFunc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeleteAccountButtonActionPerformed

    private void UpdateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateAccountButtonActionPerformed
        try {
            // TODO add your handling code here:
//        UpdateAccount m = new UpdateAccount();
//        m.setVisible(true);
//        this.dispose();
UpdateAccountController bb = new UpdateAccountController();

        } catch (RemoteException ex) {
            Logger.getLogger(AdminFunc.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_UpdateAccountButtonActionPerformed

    private void CreateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountButtonActionPerformed
        try {
            // TODO add your handling code here:
//        CreateAccount f = new CreateAccount();
//        f.setVisible(true);
//        this.dispose();
CreateAccountController a = new CreateAccountController();

        } catch (RemoteException ex) {
            Logger.getLogger(AdminFunc.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_CreateAccountButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        try {
            // TODO add your handling code here:
            LoginController cc = new LoginController();
        } catch (RemoteException ex) {
            Logger.getLogger(DoctorFunctionalties.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
 

//     LoginGUI itemloader=new LoginGUI();
//    itemloader.setVisible(true);
//    this.setVisible(false);
//    
//    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CreateAccountButton;
    private javax.swing.JButton DeleteAccountButton;
    private javax.swing.JButton NotifyAllButton;
    private javax.swing.JButton UpdateAccountButton;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
